<a href="https://colab.research.google.com/github/takahasi103/Python_basic/blob/main/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#スカラー
* スカラー（scalar）は1、5、1.2、-7などの通常の数値のこと

In [ ]:
a = 1
b = 1.5
c = -2
d = 1.5e5 # 1.5x10の5乗

# ベクトル
* ベクトルは、スカラーを直線上に並べたもの

 $$ \begin{aligned}
 \vec{p} & = \left(
    \begin{array}{c}
      p_1 \\
      p_2 \\
      \vdots \\
      p_m
    \end{array}
 \right) \\
\vec{q} & = (q_1, q_2, \cdots, q_n)
\end{aligned} $$

ベクトルには、上記の$\vec{p}$のように縦に数値を並べる縦ベクトルと、$\vec{q}$のように横に数値を並べる横ベクトルがあります。  
また、$\vec{p}$、$\vec{q}$に見られるように、ベクトルの要素を変数で表す際の添字の数は1つです。

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


# 行列
* 行列はスカラーを格子状に並べたもので、例えば以下のように表記します。

$$
   \left(
    \begin{array}{cccc}
      0 & 1 & 2 & 3 \\
      4 & 5 & 5 & 6 \\
      7 & 8 & 9 & 10 \\
    \end{array}
  \right)
$$

行は、上から1行目、2行目、3行目...と数えます。列は、左から1列目、2列目、3列目...と数えます。また、行がm個、列がn個並んでいる行列を、m x nの行列と表現します。

$$
   A = \left(
    \begin{array}{cccc}
      0 & 1 & 2 \\
      3 & 4 & 5 \\
    \end{array}
  \right)
$$
$$
   P = \left(
    \begin{array}{cccc}
      p_{11} & p_{12} & \ldots & p_{1n} \\
      p_{21} & p_{22} & \ldots & p_{2n} \\
      \vdots & \vdots & \ddots & \vdots \\
      p_{m1} & p_{m2} & \ldots & p_{mn} \\
    \end{array}
  \right)
$$

行列$A$は2x3の行列で、行列$P$はm x nの行列です。  
また、$P$に見られるように、行列の要素を変数で表す際の添字の数は2つです。

In [ ]:
import numpy as np

a = np.array([[0, 1, 2],
              [3, 4, 5]]) # 2x3の行列
print(a)
print()

b = np.array([[0, 1],
              [2, 3],
              [4, 5]]) # 3x2の行列
print(b)

[[0 1 2]
 [3 4 5]]

[[0 1]
 [2 3]
 [4 5]]


# テンソル
* テンソルはスカラーを複数の次元に並べたもので、スカラー、ベクトル、行列を含みます。

<img src="https://drive.google.com/uc?id=1AEjps0YRxZzD2Ol_rQE7tWDxnvb3Mx4P">

各要素につく添字の数を、そのテンソルの階数といいます。スカラーには添字がないので0階のテンソル、ベクトルは添字が1つなので1階のテンソル、行列は添字が2つなので2階のテンソルになります。より高次元なものは、3階のテンソル、4階のテンソル...となります。

In [ ]:
import numpy as np

a = np.array([[[0, 1, 2, 3],
               [4, 5, 6, 7],
               [8, 9, 10, 11]],

              [[11, 10, 9, 8],
               [7, 6, 5, 4],
               [3, 2, 1, 0]]]) # (2, 3, 4)の3階のテンソル
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[11 10  9  8]
  [ 7  6  5  4]
  [ 3  2  1  0]]]


# ベクトルの内積とノルム

### 内積
内積はベクトル同士の積の一種ですが、次のように定義されます。

$$ \begin{aligned}
\vec{a} & = (a_1, a_2, \cdots, a_n) \\
\vec{b} & = (b_1, b_2, \cdots, b_n)
\end{aligned} $$

のとき、

$$ \begin{aligned}
\vec{a}\cdot\vec{b} & = (a_1, a_2, \cdots, a_n)\cdot(b_1, b_2, \cdots, b_n) \\
& = (a_1b_1+a_2b_2+\cdots+a_nb_n) \\
& = \sum_{k=1}^n a_kb_k
\end{aligned} $$

内積をとる際は、2つのベクトルの要素数が同じである必要があります。  
内積は、2つのベクトルの相関を求める際に使用します。

numpyの**dot関数**で内積を求めることができる。

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])

print(np.dot(a, b)) # ベクトルaとbの内積

20


### ノルム
ノルムとはベクトルの「大きさ」を表す量です。  
人工知能でよく使われるノルムに、「$L^2$ノルム」と「$L^1ノルム$」があります。

**$L^2$ノルム**  
$L^2$ノルムは次のように$||x||_2$と表されます。ベクトルの各要素を2乗和し、平方根をとって計算します。

$$ \begin{aligned}
||x||_2 & = \sqrt {x_1^2+x_2^2+ \cdots + x_n^2} \\
& = \sqrt {\sum_{k=1}^n x_nk^2}
\end{aligned} $$

**$L^1$ノルム**  
$L^1$ノルムは次のように$||x||_1$と表されます。ベクトルの各要素の絶対値を足し合わせて計算します。

$$ \begin{aligned}
||x||_1 & = |x_1|+|x_2|+ \cdots + |x_n| \\
& = \sum_{k=1}^n |x_k|
\end{aligned} $$

**一般化されたノルム**  
ノルムをより一般化した$L^p$は以下のように表されます。

$$ \begin{aligned}
||x||_p & = (x_1^p+x_2^p+ \cdots + x_n^p)^{\frac{1}{p}} \\
& = (\sum_{k=1}^n |x_k|^p)^{\frac{1}{p}}
\end{aligned} $$

ノルムは、ディープラーニングにおいて「**正則化**」に使われます。  
正則化とは、必要以上にネットワークの学習が進んでいしまうことをパラメータを調節することにより予防することです。

numpyの**linalg.norm関数**を用いて求めることができます

In [ ]:
import numpy as np

a = np.array([1, 1, -1, -1])

print(np.linalg.norm(a))  # L2ノルム
print(np.linalg.norm(a, 1))  # L1ノルム

2.0
4.0


# 行列の積

「行列の積」という場合、次の図で示すような少々複雑な演算を指します。  
<img src="https://drive.google.com/uc?id=17Zn59TrNeEuD2P3PjnF1RnnmkCZNGicc">  

行列積では、前の行列における行の各要素と、後の行列における列の各要素を掛け合わせて総和をとり、新しい行列の要素とします。上の図では左の行列の1行目と右の行列の1列目を演算していますが、下の図では左の行列の1行目と右の行列の2列目を演算しています。
<img src="https://drive.google.com/uc?id=1o9eVnnmYFOWyF9Qaco7yqOQs2_FUu2AY">  
このようにして、左の行列の全ての行と、右の行列の全ての列の組み合わせで演算を行い、新たな行列を作ります。

$A$は2x3の行列で、$B$は3x2の行列です。
$$
   A = \left(
    \begin{array}{ccc}
      a_{11} & a_{12} & a_{13} \\
      a_{21} & a_{22} & a_{23} \\
    \end{array}
  \right)
$$

$$
   B = \left(
    \begin{array}{cc}
      b_{11} & b_{12} \\
      b_{21} & b_{22} \\
      b_{31} & b_{32} \\
    \end{array}
  \right)
$$
  
そして、$A$と$B$の積を次のように表します。

$$
   AB = \left(
    \begin{array}{ccc}
      a_{11} & a_{12} & a_{13} \\
      a_{21} & a_{22} & a_{23} \\
    \end{array}
  \right)
  \left(
    \begin{array}{cc}
      b_{11} & b_{12} \\
      b_{21} & b_{22} \\
      b_{31} & b_{32} \\
    \end{array}
  \right) \\
 = \left(
    \begin{array}{ccc}
      a_{11}b_{11}+a_{12}b_{21}+a_{13}b_{31} & a_{11}b_{12}+a_{12}b_{22}+a_{13}b_{32} \\
      a_{21}b_{11}+a_{22}b_{21}+a_{23}b_{31} & a_{21}b_{12}+a_{22}b_{22}+a_{23}b_{32} \\
    \end{array}
  \right) \\
 = \left(
    \begin{array}{ccc}
      \sum\limits_{k=1}^3 a_{1k}b_{k1} & \sum\limits_{k=1}^3 a_{1k}b_{k2} \\
      \sum\limits_{k=1}^3 a_{2k}b_{k1} & \sum\limits_{k=1}^3 a_{2k}b_{k2} \\
    \end{array}
  \right)
$$

$A$の各行と$B$の各列の各要素を掛け合わせて総和をとり、新しい行列の各要素とします。  
上記の行列積には総和の記号$\Sigma$が登場していますが、行列積は積の総和を計算する際に大活躍します。

#### 行列積の数値計算
$$  \begin{aligned} \\
AB & = \left(
    \begin{array}{cc}
      a_{11} & a_{12} & \ldots & a_{1m} \\
      a_{21} & a_{22} & \ldots & a_{2m} \\
      \vdots & \vdots & \ddots & \vdots \\
      a_{l1} & a_{l2} & \ldots & a_{lm} \\
    \end{array}
  \right)
\left(
    \begin{array}{cccc}
      b_{11} & b_{12} & \ldots & b_{1n} \\
      b_{21} & b_{22} & \ldots & b_{2n} \\
      \vdots & \vdots & \ddots & \vdots \\
      b_{m1} & b_{m2} & \ldots & b_{mn} \\
    \end{array}
  \right) \\
  & = \left(
    \begin{array}{cccc}
      \sum\limits_{k=1}^m a_{1k}b_{k1} & \sum\limits_{k=1}^m a_{1k}b_{k2} & \ldots & \sum\limits_{k=1}^m a_{1k}b_{kn} \\
       \sum\limits_{k=1}^m a_{2k}b_{k1} & \sum\limits_{k=1}^m a_{2k}b_{k2} & \ldots & \sum\limits_{k=1}^m a_{2k}b_{kn} \\
      \vdots & \vdots & \ddots & \vdots \\
      \sum\limits_{k=1}^m a_{lk}b_{k1} & \sum\limits_{k=1}^m a_{lk}b_{k2} & \ldots & \sum\limits_{k=1}^m a_{lk}b_{kn} \\
    \end{array}
  \right)
  \end{aligned}
$$

**行列積**をコードで実装  
numpyの**dot関数**を用いれば、簡単に行列積を計算することができます。

In [ ]:
import numpy as np

a = np.array([[1, 2, 3],
              [3, 2, 1]])

b = np.array([[1, 2],
              [1, 2],
              [1, 2]])

print(np.dot(a, b))

[[ 6 12]
 [ 6 12]]


#### アダマール積(要素ごとの積)

行列の各要素を掛け合わせます。

$$  \begin{aligned} \\
   A & = \left(
    \begin{array}{cccc}
      a_{11} & a_{12} & \ldots & a_{1n} \\
      a_{21} & a_{22} & \ldots & a_{2n} \\
      \vdots & \vdots & \ddots & \vdots \\
      a_{m1} & a_{m2} & \ldots & a_{mn}
    \end{array}
  \right) \\
   B & = \left(
    \begin{array}{cccc}
      b_{11} & b_{12} & \ldots & b_{1n} \\
      b_{21} & b_{22} & \ldots & b_{2n} \\
      \vdots & \vdots & \ddots & \vdots \\
      b_{m1} & b_{m2} & \ldots & b_{mn}
    \end{array}
  \right)
\end{aligned} $$

これらの行列の要素ごとの積は、演算子$\circ$を用いて次のように表すことができます。

$$
   A\circ B = \left(
    \begin{array}{cccc}
      a_{11}b_{11} & a_{12}b_{12} & \ldots & a_{1n}b_{1n} \\
      a_{21}b_{21} & a_{22}b_{22} & \ldots & a_{2n}b_{2n} \\
      \vdots & \vdots & \ddots & \vdots \\
      a_{m1}b_{m1} & a_{m2}b_{m2} & \ldots & a_{mn}b_{mn}
    \end{array}
  \right)
$$

例えば次ような場合、

$$ \begin{aligned} \\
   A  & = \left(
    \begin{array}{ccc}
      0 & 1 & 2 \\
      3 & 4 & 5 \\
      6 & 7 & 8
    \end{array}
  \right) \\
  B  & = \left(
    \begin{array}{ccc}
      0 & 1 & 2 \\
      2 & 0 & 1 \\
      1 & 2 & 0
    \end{array}
  \right)
\end{aligned}
$$

$A$と$B$の要素ごとの積は次のようになります。

$$ \begin{aligned} \\
  A\circ B  & = \left(
    \begin{array}{ccc}
      0\times 0 & 1\times 1 & 2\times 2 \\
      3\times 2 & 4\times 0 & 5\times 1 \\
      6\times 1 & 7\times 2 & 8\times 0
    \end{array}
  \right) \\
  & = \left(
    \begin{array}{ccc}
      0 & 1 & 4 \\
      6 & 0 & 5 \\
      6 & 14 & 0
    \end{array}
  \right)
\end{aligned}
$$

**アダマール積**をコードで実装  
要素ごとの演算にはスカラーの積の演算子`*`を使います。

In [ ]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

b = np.array([[1, 2, 3],
              [1, 2, 3],
              [1, 2, 3]])

# 要素ごとの積を計算するためには、配列の形状が同じである必要があります。

print(a*b)

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


# 転置

行列の行と列を入れ替えます。  
例えば行列$A$の転置行列は$A^{\mathrm{T}}$と表します。  

$$  \begin{aligned} \\
   A & = \left(
    \begin{array}{ccc}
      1 & 2 & 3 \\
      4 & 5 & 6 \\
    \end{array}
  \right) \\
   A^{\mathrm{T}} & = \left(
    \begin{array}{cc}
      1 & 4 \\
      2 & 5 \\
      3 & 6 \\
    \end{array}
  \right) \\
\end{aligned} $$

**転置**をコードで実装  
numpyにおいては、行列を表す配列名の後に`.T`を付けると転置されます。

In [2]:
import numpy as np

a = np.array([[1, 2, 3],
             [4, 5, 6]])

print(a)
print()

print(a.T) # 転置

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


#### 行列積と転置
行列積においては、基本的に前の行列の列数と、後ろの行列の行数が一致する必要があります。しかしながら、一致しなくても転置により行列積が可能になる場合があります。

$$  \begin{aligned} \\
   A & = \left(
    \begin{array}{ccc}
      1 & 2 & 3 \\
      4 & 5 & 6 \\
    \end{array}
  \right) \\
  B & = \left(
    \begin{array}{ccc}
      9 & 8 & 7 \\
      6 & 5 & 4 \\
    \end{array}
  \right) \\
\end{aligned} $$  
この場合は、行列$A$の**列数が3**であり、行列$B$の**行数が2**で等しくないので、行列積はできません。しかしながら、行列$B$を転置することにより、行列積が可能になります。

$$  \begin{aligned} \\
   A & = \left(
    \begin{array}{ccc}
      1 & 2 & 3 \\
      4 & 5 & 6 \\
    \end{array}
  \right) \\
  B^T & = \left(
    \begin{array}{ccc}
      9 & 6 \\
      8 & 5 \\
      7 & 4 \\
    \end{array}
  \right) \\
\end{aligned} $$   
行列$A$の列数と、行列$B^{\mathrm{T}}$の行数が等しくなり、行列積が計算できるようになりました。

In [3]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[9, 8, 7],
              [6, 5, 4]])

print(np.dot(a, b.T))

[[ 46  28]
 [118  73]]
