<a href="https://colab.research.google.com/github/takahasi103/Python_basic/blob/main/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#スカラー
* スカラー（scalar）は1、5、1.2、-7などの通常の数値のこと

In [ ]:
a = 1
b = 1.5
c = -2
d = 1.5e5 # 1.5x10の5乗

# ベクトル
* ベクトルは、スカラーを直線上に並べたもの

 $$ \begin{aligned}
 \vec{p} & = \left(
    \begin{array}{c}
      p_1 \\
      p_2 \\
      \vdots \\
      p_m
    \end{array}
 \right) \\
\vec{q} & = (q_1, q_2, \cdots, q_n)
\end{aligned} $$

ベクトルには、上記の$\vec{p}$のように縦に数値を並べる縦ベクトルと、$\vec{q}$のように横に数値を並べる横ベクトルがあります。  
また、$\vec{p}$、$\vec{q}$に見られるように、ベクトルの要素を変数で表す際の添字の数は1つです。

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


# 行列
* 行列はスカラーを格子状に並べたもので、例えば以下のように表記します。

$$
   \left(
    \begin{array}{cccc}
      0 & 1 & 2 & 3 \\
      4 & 5 & 5 & 6 \\
      7 & 8 & 9 & 10 \\
    \end{array}
  \right)
$$

行は、上から1行目、2行目、3行目...と数えます。列は、左から1列目、2列目、3列目...と数えます。また、行がm個、列がn個並んでいる行列を、m x nの行列と表現します。

$$
   A = \left(
    \begin{array}{cccc}
      0 & 1 & 2 \\
      3 & 4 & 5 \\
    \end{array}
  \right)
$$
$$
   P = \left(
    \begin{array}{cccc}
      p_{11} & p_{12} & \ldots & p_{1n} \\
      p_{21} & p_{22} & \ldots & p_{2n} \\
      \vdots & \vdots & \ddots & \vdots \\
      p_{m1} & p_{m2} & \ldots & p_{mn} \\
    \end{array}
  \right)
$$

行列$A$は2x3の行列で、行列$P$はm x nの行列です。  
また、$P$に見られるように、行列の要素を変数で表す際の添字の数は2つです。

In [ ]:
import numpy as np

a = np.array([[0, 1, 2],
              [3, 4, 5]]) # 2x3の行列
print(a)
print()

b = np.array([[0, 1],
              [2, 3],
              [4, 5]]) # 3x2の行列
print(b)

[[0 1 2]
 [3 4 5]]

[[0 1]
 [2 3]
 [4 5]]


# テンソル
* テンソルはスカラーを複数の次元に並べたもので、スカラー、ベクトル、行列を含みます。

<img src="https://drive.google.com/uc?id=1AEjps0YRxZzD2Ol_rQE7tWDxnvb3Mx4P">

各要素につく添字の数を、そのテンソルの階数といいます。スカラーには添字がないので0階のテンソル、ベクトルは添字が1つなので1階のテンソル、行列は添字が2つなので2階のテンソルになります。より高次元なものは、3階のテンソル、4階のテンソル...となります。

In [ ]:
import numpy as np

a = np.array([[[0, 1, 2, 3],
               [4, 5, 6, 7],
               [8, 9, 10, 11]],

              [[11, 10, 9, 8],
               [7, 6, 5, 4],
               [3, 2, 1, 0]]]) # (2, 3, 4)の3階のテンソル
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[11 10  9  8]
  [ 7  6  5  4]
  [ 3  2  1  0]]]


# ベクトルの内積とノルム

### 内積
内積はベクトル同士の積の一種ですが、次のように定義されます。

$$ \begin{aligned}
\vec{a} & = (a_1, a_2, \cdots, a_n) \\
\vec{b} & = (b_1, b_2, \cdots, b_n)
\end{aligned} $$

のとき、

$$ \begin{aligned}
\vec{a}\cdot\vec{b} & = (a_1, a_2, \cdots, a_n)\cdot(b_1, b_2, \cdots, b_n) \\
& = (a_1b_1+a_2b_2+\cdots+a_nb_n) \\
& = \sum_{k=1}^n a_kb_k
\end{aligned} $$

内積をとる際は、2つのベクトルの要素数が同じである必要があります。  
内積は、2つのベクトルの相関を求める際に使用します。

numpyの**dot関数**で内積を求めることができる。

In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])

print(np.dot(a, b)) # ベクトルaとbの内積

20


### ノルム
ノルムとはベクトルの「大きさ」を表す量です。  
人工知能でよく使われるノルムに、「$L^2$ノルム」と「$L^1ノルム$」があります。

**$L^2$ノルム**  
$L^2$ノルムは次のように$||x||_2$と表されます。ベクトルの各要素を2乗和し、平方根をとって計算します。

$$ \begin{aligned}
||x||_2 & = \sqrt {x_1^2+x_2^2+ \cdots + x_n^2} \\
& = \sqrt {\sum_{k=1}^n x_nk^2}
\end{aligned} $$

**$L^1$ノルム**  
$L^1$ノルムは次のように$||x||_1$と表されます。ベクトルの各要素の絶対値を足し合わせて計算します。

$$ \begin{aligned}
||x||_1 & = |x_1|+|x_2|+ \cdots + |x_n| \\
& = \sum_{k=1}^n |x_k|
\end{aligned} $$

**一般化されたノルム**  
ノルムをより一般化した$L^p$は以下のように表されます。

$$ \begin{aligned}
||x||_p & = (x_1^p+x_2^p+ \cdots + x_n^p)^{\frac{1}{p}} \\
& = (\sum_{k=1}^n |x_k|^p)^{\frac{1}{p}}
\end{aligned} $$

ノルムは、ディープラーニングにおいて「**正則化**」に使われます。  
正則化とは、必要以上にネットワークの学習が進んでいしまうことをパラメータを調節することにより予防することです。

numpyの**linalg.norm関数**を用いて求めることができます

In [3]:
import numpy as np

a = np.array([1, 1, -1, -1])

print(np.linalg.norm(a))  # L2ノルム
print(np.linalg.norm(a, 1))  # L1ノルム

2.0
4.0
