<a href="https://colab.research.google.com/github/takahasi103/Python_basic/blob/main/numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPyの基礎

## NumPyとは
Pythonの拡張モジュールです。
NumPyはシンプルな表記で効率的なデータの操作を可能にします。

#### NumPyの配列
NumPyの配列は、NumPyのarray関数を使うことでPythonのリストから簡単に作ることができます。

In [ ]:
import numpy as np # NumPyを読み込む

a = np.array([1, 2, 3, 4, 5]) # PythonのリストからNumPyの配列を作成
print(a)


[1 2 3 4 5]


In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]]) # 2重のリストから2次元配列を作成
print(a)

print()

b = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]]) # 3重のリストから3次元配列を作成
print(b)

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 配列の演算

In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

print()

print(a + 2) # 各要素に2を足す

print()

print(a * 2) # 各要素に2をかける

[[1 2 3]
 [4 5 6]]

[[3 4 5]
 [6 7 8]]

[[ 2  4  6]
 [ 8 10 12]]


**配列同士の演算**

In [ ]:
from re import A
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[3, 2, 1], [6, 5, 4], [9, 8, 7]])
print(a)
print()
print(b)

print()

print(a + b)

print()

print(a * b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[3 2 1]
 [6 5 4]
 [9 8 7]]

[[ 4  4  4]
 [10 10 10]
 [16 16 16]]

[[ 3  4  3]
 [24 25 24]
 [63 64 63]]


#### 関数と配列
関数の引数や返り値としてNumPyの配列を使うことができます。  
以下の関数`add`は、引数として配列を受け取り、返り値として配列を返しています。

In [ ]:
import numpy as np

def add(x):
    n = x + 3
    return n

a = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
b = add(a) # 引数として配列を渡す

print(b)

[[ 3  4  5  6  7]
 [ 8  9 10 11 12]]


In [ ]:
import numpy as np

a = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])

print("合計:" + " " +  str(np.sum(a)))
print("平均:" + " " +  str(np.average(a)))
print("最大値:" + " " +  str(np.max(a)))
print("最小値:" + " " +  str(np.min(a)))

合計: 45
平均: 4.5
最大値: 9
最小値: 0


#### linsppace関数
ある区間を50に等間隔で区切ってNumPyの配列にします。  
この配列を、グラフの横軸の値としてよく使います。

In [1]:
import numpy as np

x = np.linspace(-5, 5)  # -5から5まで50に区切る

print(x)
print(len(x))  # xの要素数

[-5.         -4.79591837 -4.59183673 -4.3877551  -4.18367347 -3.97959184
 -3.7755102  -3.57142857 -3.36734694 -3.16326531 -2.95918367 -2.75510204
 -2.55102041 -2.34693878 -2.14285714 -1.93877551 -1.73469388 -1.53061224
 -1.32653061 -1.12244898 -0.91836735 -0.71428571 -0.51020408 -0.30612245
 -0.10204082  0.10204082  0.30612245  0.51020408  0.71428571  0.91836735
  1.12244898  1.32653061  1.53061224  1.73469388  1.93877551  2.14285714
  2.34693878  2.55102041  2.75510204  2.95918367  3.16326531  3.36734694
  3.57142857  3.7755102   3.97959184  4.18367347  4.3877551   4.59183673
  4.79591837  5.        ]
50


In [ ]:
# 異なるデータ型がある場合、最初の要素のデータ型に変換
np.array(['p', 1, 2, 3])

array(['p', '1', '2', '3'], dtype='<U21')

`.arange()`で数値が順番に並んだndarrayを作成できる

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(1,8) # (始点, 配列数)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
a = np.zeros([3,5]) # 要素がすべて0
print(a)

b= np.ones([3,5]) # 要素がすべて1
print(b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
from numpy.random import *
rand(2,3) # 0~1の間でランダムに数値を取得

array([[0.38503216, 0.50808978, 0.98440502],
       [0.46674634, 0.28803783, 0.11488345]])

In [ ]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

行列の大きさを確認

In [ ]:
a.shape # (行,列)

(3, 5)

行列の軸数（次元）を確認

In [ ]:
a.ndim

2

行列のデータ型を確認

In [ ]:
type(a)

numpy.ndarray

行列の配列要素を確認

In [ ]:
a.dtype

dtype('int64')

スライス

In [ ]:
a = np.arange(10)
print(a)

print(a[4:8]) # 始点:8以下まで

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7]


「0」以外が入っているインデックスを取得

In [ ]:
b = np.nonzero([3, 4, 0, 0, 5, 0, 0])
print(b)

(array([0, 1, 4]),)


最小値と最大値を出力

In [ ]:
a = np.random.random((10,10))

print(a)

datamin, datamax = a.min(), a.max() # 最小値, 最大値
print("最小値:" + str(datamin))
print("最大値:" + str(datamax))

[[0.57535447 0.47300318 0.58241885 0.54136298 0.57899747 0.19381732
  0.29460217 0.41764741 0.56913927 0.32073029]
 [0.72104018 0.03496081 0.29004532 0.61755194 0.8586109  0.63481403
  0.47218713 0.67033892 0.73188583 0.71025875]
 [0.3671675  0.52901482 0.07439707 0.56732028 0.51267015 0.83809608
  0.97343299 0.52044082 0.8123824  0.7771512 ]
 [0.68963963 0.16796942 0.86526683 0.35245224 0.30143831 0.22729291
  0.98217703 0.72374644 0.74014345 0.55954183]
 [0.25734745 0.23272453 0.46088335 0.465984   0.92978853 0.66433841
  0.45514873 0.68113733 0.3630658  0.35334685]
 [0.6310144  0.80827839 0.89956099 0.00758224 0.83761598 0.31978115
  0.9272885  0.01024489 0.02525395 0.99087353]
 [0.58362632 0.49688529 0.09811622 0.25417412 0.46273551 0.6053844
  0.49705302 0.13394082 0.20236307 0.08462028]
 [0.37326189 0.62742398 0.84329511 0.15344351 0.72149977 0.29852789
  0.67021829 0.39043926 0.69593651 0.78148939]
 [0.10733081 0.81687541 0.47130237 0.24568126 0.19801501 0.04533718
  0.96592777 

平均値を出力

In [ ]:
a = np.random.random((10,10))
m = a.mean() #平均値
print(m)

0.53147748995404
