<a href="https://colab.research.google.com/github/takahasi103/Python_basic/blob/main/numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# unmpyとは
数値計算の際に利用されるライブラリ

`np.array()`で**「ndarray」**を作成することができる
**ndarray**はnumpyが持つ独自のデータ構造で、ndarrayを使用して計算することで、高速な処理が可能

In [8]:
# ndarryの作成方法

import numpy as np # numpyを読み込む

np.array([1, 2, 3])


array([1, 2, 3])

In [9]:
# 異なるデータ型がある場合、最初の要素のデータ型に変換
np.array(['p', 1, 2, 3])

array(['p', '1', '2', '3'], dtype='<U21')

`.arange()`で数値が順番に並んだndarrayを作成できる

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
np.arange(1,8) # (始点, 配列数)

array([1, 2, 3, 4, 5, 6, 7])