<a href="https://colab.research.google.com/github/takahasi103/Python_basic/blob/main/numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# unmpyとは
数値計算の際に利用されるライブラリ

`np.array()`で**「ndarray」**を作成することができる
**ndarray**はnumpyが持つ独自のデータ構造で、ndarrayを使用して計算することで、高速な処理が可能

In [1]:
# ndarryの作成方法

import numpy as np # numpyを読み込む

np.array([1, 2, 3])


array([1, 2, 3])

In [ ]:
# 異なるデータ型がある場合、最初の要素のデータ型に変換
np.array(['p', 1, 2, 3])

array(['p', '1', '2', '3'], dtype='<U21')

`.arange()`で数値が順番に並んだndarrayを作成できる

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(1,8) # (始点, 配列数)

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
a = np.zeros([3,5]) # 要素がすべて0
print(a)

b= np.ones([3,5]) # 要素がすべて1
print(b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
from numpy.random import *
rand(2,3) # 0~1の間でランダムに数値を取得

array([[0.38503216, 0.50808978, 0.98440502],
       [0.46674634, 0.28803783, 0.11488345]])

In [7]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

行列の大きさを確認

In [8]:
a.shape # (行,列)

(3, 5)