<a href="https://colab.research.google.com/github/takahasi103/Python_basic/blob/main/numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpyとは
数値計算の際に利用されるライブラリ

`np.array()`で**「ndarray」**を作成することができる
**ndarray**はnumpyが持つ独自のデータ構造で、ndarrayを使用して計算することで、高速な処理が可能

In [1]:
# ndarryの作成方法

import numpy as np # numpyを読み込む

np.array([1, 2, 3])


array([1, 2, 3])

In [ ]:
# 異なるデータ型がある場合、最初の要素のデータ型に変換
np.array(['p', 1, 2, 3])

array(['p', '1', '2', '3'], dtype='<U21')

`.arange()`で数値が順番に並んだndarrayを作成できる

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(1,8) # (始点, 配列数)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
a = np.zeros([3,5]) # 要素がすべて0
print(a)

b= np.ones([3,5]) # 要素がすべて1
print(b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
from numpy.random import *
rand(2,3) # 0~1の間でランダムに数値を取得

array([[0.38503216, 0.50808978, 0.98440502],
       [0.46674634, 0.28803783, 0.11488345]])

In [2]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

行列の大きさを確認

In [ ]:
a.shape # (行,列)

(3, 5)

行列の軸数（次元）を確認

In [ ]:
a.ndim

2

行列のデータ型を確認

In [ ]:
type(a)

numpy.ndarray

行列の配列要素を確認

In [ ]:
a.dtype

dtype('int64')

スライス

In [3]:
a = np.arange(10)
print(a)

print(a[4:8]) # 始点:8以下まで

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7]


「0」以外が入っているインデックスを取得

In [4]:
b = np.nonzero([3, 4, 0, 0, 5, 0, 0])
print(b)

(array([0, 1, 4]),)


最小値と最大値を出力

In [11]:
a = np.random.random((10,10))

print(a)

datamin, datamax = a.min(), a.max() # 最小値, 最大値
print("最小値:" + str(datamin))
print("最大値:" + str(datamax))

[[0.57535447 0.47300318 0.58241885 0.54136298 0.57899747 0.19381732
  0.29460217 0.41764741 0.56913927 0.32073029]
 [0.72104018 0.03496081 0.29004532 0.61755194 0.8586109  0.63481403
  0.47218713 0.67033892 0.73188583 0.71025875]
 [0.3671675  0.52901482 0.07439707 0.56732028 0.51267015 0.83809608
  0.97343299 0.52044082 0.8123824  0.7771512 ]
 [0.68963963 0.16796942 0.86526683 0.35245224 0.30143831 0.22729291
  0.98217703 0.72374644 0.74014345 0.55954183]
 [0.25734745 0.23272453 0.46088335 0.465984   0.92978853 0.66433841
  0.45514873 0.68113733 0.3630658  0.35334685]
 [0.6310144  0.80827839 0.89956099 0.00758224 0.83761598 0.31978115
  0.9272885  0.01024489 0.02525395 0.99087353]
 [0.58362632 0.49688529 0.09811622 0.25417412 0.46273551 0.6053844
  0.49705302 0.13394082 0.20236307 0.08462028]
 [0.37326189 0.62742398 0.84329511 0.15344351 0.72149977 0.29852789
  0.67021829 0.39043926 0.69593651 0.78148939]
 [0.10733081 0.81687541 0.47130237 0.24568126 0.19801501 0.04533718
  0.96592777 

平均値を出力

In [12]:
a = np.random.random((10,10))
m = a.mean() #平均値
print(m)

0.53147748995404
