<a href="https://colab.research.google.com/github/takahasi103/Python_basic/blob/main/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#スカラー
* スカラー（scalar）は1、5、1.2、-7などの通常の数値のこと

In [ ]:
a = 1
b = 1.5
c = -2
d = 1.5e5 # 1.5x10の5乗

# ベクトル
* ベクトルは、スカラーを直線上に並べたもの

 $$ \begin{aligned}
 \vec{p} & = \left(
    \begin{array}{c}
      p_1 \\
      p_2 \\
      \vdots \\
      p_m
    \end{array}
 \right) \\
\vec{q} & = (q_1, q_2, \cdots, q_n)
\end{aligned} $$

ベクトルには、上記の$\vec{p}$のように縦に数値を並べる縦ベクトルと、$\vec{q}$のように横に数値を並べる横ベクトルがあります。  
また、$\vec{p}$、$\vec{q}$に見られるように、ベクトルの要素を変数で表す際の添字の数は1つです。

In [3]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


# 行列
* 行列はスカラーを格子状に並べたもので、例えば以下のように表記します。

$$
   \left(
    \begin{array}{cccc}
      0 & 1 & 2 & 3 \\
      4 & 5 & 5 & 6 \\
      7 & 8 & 9 & 10 \\
    \end{array}
  \right)
$$

行は、上から1行目、2行目、3行目...と数えます。列は、左から1列目、2列目、3列目...と数えます。また、行がm個、列がn個並んでいる行列を、m x nの行列と表現します。

$$
   A = \left(
    \begin{array}{cccc}
      0 & 1 & 2 \\
      3 & 4 & 5 \\
    \end{array}
  \right)
$$
$$
   P = \left(
    \begin{array}{cccc}
      p_{11} & p_{12} & \ldots & p_{1n} \\
      p_{21} & p_{22} & \ldots & p_{2n} \\
      \vdots & \vdots & \ddots & \vdots \\
      p_{m1} & p_{m2} & \ldots & p_{mn} \\
    \end{array}
  \right)
$$

行列$A$は2x3の行列で、行列$P$はm x nの行列です。  
また、$P$に見られるように、行列の要素を変数で表す際の添字の数は2つです。

In [4]:
import numpy as np

a = np.array([[0, 1, 2],
              [3, 4, 5]]) # 2x3の行列
print(a)
print()

b = np.array([[0, 1],
              [2, 3],
              [4, 5]]) # 3x2の行列
print(b)

[[0 1 2]
 [3 4 5]]

[[0 1]
 [2 3]
 [4 5]]
